### ISSUE TITLE
Is there a way to fetch <script> tags?

### ISSUE THREAD

**Issue by szabgab** [tokuhirom/Web-Query#48]
This does not work:

```
#!/usr/bin/perl
use strict;
use warnings;
use Test::More;

plan tests => 1;

use Web::Query qw(wq);


my $html = <<'HTML';
<html>
<script>
console.log('Hello World');
</script>
</html>
HTML

my @text;
my $q = Web::Query->new_from_html($html);
isa_ok $q, 'Web::Query';
$q->find('script')->each(sub {
    my ($i, $elem) = @_;
    push @text, $elem->text;
});

diag explain \@text;
```

Results in
```
1..1
ok 1 - An object of class 'Web::Query' isa 'Web::Query'
# [
#   ''
# ]
```

**Comment by yanick** [comment]
use `->html` instead of `->text`

**Comment by szabgab** [comment]
:+1:

**Comment by szabgab** [comment]
Actually that did not work well for me as this method returned the JavaScript code after running it through some html escape thing. So I have ```&#39;``` and ```&quot;``` in the returned string instead of the plain JavaScript.

**Comment by yanick** [comment]
That's because for html `&quot;` and `'` are the same. The special treatment of `<script>` is done by HTML::TreeBuilder. I've added a troubleshooting entry in the POD for this case. Basically, you have two options:

* use `Web::Query::LibXML`, which doesn't do anything special with `<script>`.
* unescape the html returned by `html()`.
